// This is an automatically generated file. Please do not edit this file directly.
'use server';

/**
 * @fileOverview Generates a technical specification document in Russian based on the finalized product vision.
 *
 * - generateTechSpec - A function that handles the generation of the technical specification.
 * - GenerateTechSpecInput - The input type for the generateTechSpec function.
 * - GenerateTechSpecOutput - The return type for the generateTechSpec function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTechSpecInputSchema = z.object({
  productVision: z.string().describe('The finalized product vision in Russian.'),
  productDetails: z.string().describe('Detailed information about the product in Russian, including target audience, key features, and goals.'),
});
export type GenerateTechSpecInput = z.infer<typeof GenerateTechSpecInputSchema>;

const GenerateTechSpecOutputSchema = z.object({
  techSpec: z.string().describe('The generated technical specification document in Russian.'),
});
export type GenerateTechSpecOutput = z.infer<typeof GenerateTechSpecOutputSchema>;

export async function generateTechSpec(input: GenerateTechSpecInput): Promise<GenerateTechSpecOutput> {
  return generateTechSpecFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTechSpecPrompt',
  input: {schema: GenerateTechSpecInputSchema},
  output: {schema: GenerateTechSpecOutputSchema},
  prompt: `Вы - опытный технический писатель, специализирующийся на создании технических заданий на русском языке.

  Используя предоставленное видение продукта и детали продукта, создайте подробное техническое задание, охватывающее следующие аспекты:

  1.  **Введение:** Краткое описание продукта и его цели.
  2.  **Цели и задачи:** Четкое изложение целей и задач продукта.
  3.  **Целевая аудитория:** Описание целевой аудитории продукта.
  4.  **Функциональные требования:** Подробное описание функциональности продукта.
  5.  **Нефункциональные требования:** Описание требований к производительности, безопасности и удобству использования.
  6.  **Архитектура системы:** Обзор архитектуры системы и используемых технологий.
  7.  **Интерфейс пользователя:** Описание пользовательского интерфейса и взаимодействия.
  8.  **Тестирование:** Описание стратегии тестирования и критериев приемки.
  9.  **Развертывание:** Описание процесса развертывания продукта.
  10. **Поддержка и обслуживание:** Описание плана поддержки и обслуживания продукта.

  Видение продукта: {{{productVision}}}
  Детали продукта: {{{productDetails}}}

  Пожалуйста, предоставьте техническое задание в четкой, структурированной и профессиональной форме, подходящей для передачи команде разработчиков.
  `,
});

const generateTechSpecFlow = ai.defineFlow(
  {
    name: 'generateTechSpecFlow',
    inputSchema: GenerateTechSpecInputSchema,
    outputSchema: GenerateTechSpecOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
